/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.12.12
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QColumnView>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QFrame>
#include <QtWidgets/QGraphicsView>
#include <QtWidgets/QGridLayout>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralwidget;
    QWidget *widget_nav;
    QPushButton *pushButton_personal;
    QPushButton *pushButton_main;
    QPushButton *pushButton_product;
    QColumnView *columnView;
    QWidget *widget_main;
    QLabel *label_5;
    QLabel *label_color;
    QFrame *Line_2;
    QLabel *label_4;
    QGraphicsView *graphicsView_actionBar;
    QGraphicsView *graphicsView_color;
    QGraphicsView *graphicsView_saveOrClear;
    QFrame *Line_4;
    QLabel *label_2;
    QPushButton *pushButton_clear;
    QPushButton *pushButton_pen;
    QFrame *Line_3;
    QGraphicsView *graphicsView_drawPen;
    QPushButton *pushButton_circle;
    QPushButton *pushButton_colorMore;
    QLabel *label;
    QLabel *label_3;
    QPushButton *pushButton_line;
    QPushButton *pushButton_rectangle;
    QComboBox *comboBox_width;
    QFrame *Line_6;
    QLabel *label_6;
    QGraphicsView *graphicsView_width;
    QWidget *layoutWidget;
    QGridLayout *gridLayout;
    QPushButton *pushButton_white;
    QPushButton *pushButton_black;
    QPushButton *pushButton_green;
    QPushButton *pushButton_purple;
    QPushButton *pushButton_blue;
    QPushButton *pushButton_yellow;
    QPushButton *pushButton_red;
    QPushButton *pushButton_cyan;
    QPushButton *pushButton_save;
    QFrame *Line_5;
    QFrame *Line_8;
    QGraphicsView *graphicsView_RobbEr;
    QPushButton *pushButton_about;
    QLabel *label_7;
    QWidget *widget_product;
    QWidget *widget_about;
    QLabel *label_user;
    QLabel *label_username;
    QLabel *label_pass;
    QPushButton *pushButton_change;
    QLabel *label_change;
    QLineEdit *lineEdit_change;
    QPushButton *pushButton_yes;
    QPushButton *pushButton_no;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QString::fromUtf8("MainWindow"));
        MainWindow->setEnabled(true);
        MainWindow->resize(900, 750);
        QSizePolicy sizePolicy(QSizePolicy::Fixed, QSizePolicy::Fixed);
        sizePolicy.setHorizontalStretch(0);
        sizePolicy.setVerticalStretch(0);
        sizePolicy.setHeightForWidth(MainWindow->sizePolicy().hasHeightForWidth());
        MainWindow->setSizePolicy(sizePolicy);
        MainWindow->setMinimumSize(QSize(900, 750));
        MainWindow->setMaximumSize(QSize(900, 750));
        centralwidget = new QWidget(MainWindow);
        centralwidget->setObjectName(QString::fromUtf8("centralwidget"));
        sizePolicy.setHeightForWidth(centralwidget->sizePolicy().hasHeightForWidth());
        centralwidget->setSizePolicy(sizePolicy);
        centralwidget->setMinimumSize(QSize(900, 750));
        centralwidget->setMaximumSize(QSize(900, 750));
        widget_nav = new QWidget(centralwidget);
        widget_nav->setObjectName(QString::fromUtf8("widget_nav"));
        widget_nav->setGeometry(QRect(0, 0, 900, 100));
        sizePolicy.setHeightForWidth(widget_nav->sizePolicy().hasHeightForWidth());
        widget_nav->setSizePolicy(sizePolicy);
        widget_nav->setMinimumSize(QSize(900, 100));
        widget_nav->setMaximumSize(QSize(900, 100));
        pushButton_personal = new QPushButton(widget_nav);
        pushButton_personal->setObjectName(QString::fromUtf8("pushButton_personal"));
        pushButton_personal->setGeometry(QRect(185, 12, 80, 80));
        sizePolicy.setHeightForWidth(pushButton_personal->sizePolicy().hasHeightForWidth());
        pushButton_personal->setSizePolicy(sizePolicy);
        pushButton_personal->setMinimumSize(QSize(80, 80));
        pushButton_personal->setMaximumSize(QSize(80, 80));
        pushButton_personal->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_main = new QPushButton(widget_nav);
        pushButton_main->setObjectName(QString::fromUtf8("pushButton_main"));
        pushButton_main->setGeometry(QRect(12, 12, 80, 80));
        sizePolicy.setHeightForWidth(pushButton_main->sizePolicy().hasHeightForWidth());
        pushButton_main->setSizePolicy(sizePolicy);
        pushButton_main->setMinimumSize(QSize(80, 80));
        pushButton_main->setMaximumSize(QSize(80, 80));
        pushButton_main->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_product = new QPushButton(widget_nav);
        pushButton_product->setObjectName(QString::fromUtf8("pushButton_product"));
        pushButton_product->setGeometry(QRect(99, 12, 80, 80));
        sizePolicy.setHeightForWidth(pushButton_product->sizePolicy().hasHeightForWidth());
        pushButton_product->setSizePolicy(sizePolicy);
        pushButton_product->setMinimumSize(QSize(80, 80));
        pushButton_product->setMaximumSize(QSize(80, 80));
        pushButton_product->setCursor(QCursor(Qt::PointingHandCursor));
        columnView = new QColumnView(widget_nav);
        columnView->setObjectName(QString::fromUtf8("columnView"));
        columnView->setGeometry(QRect(0, 0, 900, 100));
        sizePolicy.setHeightForWidth(columnView->sizePolicy().hasHeightForWidth());
        columnView->setSizePolicy(sizePolicy);
        columnView->setMinimumSize(QSize(900, 100));
        columnView->setMaximumSize(QSize(900, 100));
        columnView->raise();
        pushButton_personal->raise();
        pushButton_main->raise();
        pushButton_product->raise();
        widget_main = new QWidget(centralwidget);
        widget_main->setObjectName(QString::fromUtf8("widget_main"));
        widget_main->setGeometry(QRect(0, 100, 900, 650));
        sizePolicy.setHeightForWidth(widget_main->sizePolicy().hasHeightForWidth());
        widget_main->setSizePolicy(sizePolicy);
        widget_main->setMinimumSize(QSize(900, 650));
        widget_main->setMaximumSize(QSize(900, 650));
        label_5 = new QLabel(widget_main);
        label_5->setObjectName(QString::fromUtf8("label_5"));
        label_5->setGeometry(QRect(650, 680, 30, 30));
        sizePolicy.setHeightForWidth(label_5->sizePolicy().hasHeightForWidth());
        label_5->setSizePolicy(sizePolicy);
        label_5->setMinimumSize(QSize(30, 30));
        label_5->setMaximumSize(QSize(30, 30));
        QFont font;
        font.setPointSize(15);
        font.setBold(true);
        font.setUnderline(false);
        font.setWeight(75);
        label_5->setFont(font);
        label_color = new QLabel(widget_main);
        label_color->setObjectName(QString::fromUtf8("label_color"));
        label_color->setGeometry(QRect(820, 400, 50, 25));
        sizePolicy.setHeightForWidth(label_color->sizePolicy().hasHeightForWidth());
        label_color->setSizePolicy(sizePolicy);
        label_color->setMinimumSize(QSize(50, 25));
        label_color->setMaximumSize(QSize(50, 25));
        QFont font1;
        font1.setFamily(QString::fromUtf8("\345\215\216\346\226\207\345\256\213\344\275\223"));
        font1.setPointSize(9);
        font1.setBold(false);
        font1.setWeight(50);
        label_color->setFont(font1);
        label_color->setAlignment(Qt::AlignCenter);
        Line_2 = new QFrame(widget_main);
        Line_2->setObjectName(QString::fromUtf8("Line_2"));
        Line_2->setGeometry(QRect(730, 105, 140, 5));
        sizePolicy.setHeightForWidth(Line_2->sizePolicy().hasHeightForWidth());
        Line_2->setSizePolicy(sizePolicy);
        Line_2->setMinimumSize(QSize(140, 5));
        Line_2->setMaximumSize(QSize(140, 5));
        Line_2->setFrameShape(QFrame::HLine);
        Line_2->setFrameShadow(QFrame::Sunken);
        label_4 = new QLabel(widget_main);
        label_4->setObjectName(QString::fromUtf8("label_4"));
        label_4->setGeometry(QRect(725, 570, 150, 20));
        sizePolicy.setHeightForWidth(label_4->sizePolicy().hasHeightForWidth());
        label_4->setSizePolicy(sizePolicy);
        label_4->setMinimumSize(QSize(150, 20));
        label_4->setMaximumSize(QSize(150, 20));
        QFont font2;
        font2.setPointSize(10);
        font2.setBold(true);
        font2.setWeight(75);
        label_4->setFont(font2);
        label_4->setAlignment(Qt::AlignCenter);
        graphicsView_actionBar = new QGraphicsView(widget_main);
        graphicsView_actionBar->setObjectName(QString::fromUtf8("graphicsView_actionBar"));
        graphicsView_actionBar->setGeometry(QRect(700, 0, 200, 650));
        graphicsView_actionBar->setStyleSheet(QString::fromUtf8("background-image: url(:/widget/Picture/Background_2.jpg);"));
        graphicsView_color = new QGraphicsView(widget_main);
        graphicsView_color->setObjectName(QString::fromUtf8("graphicsView_color"));
        graphicsView_color->setGeometry(QRect(715, 310, 170, 120));
        sizePolicy.setHeightForWidth(graphicsView_color->sizePolicy().hasHeightForWidth());
        graphicsView_color->setSizePolicy(sizePolicy);
        graphicsView_color->setMinimumSize(QSize(170, 120));
        graphicsView_color->setMaximumSize(QSize(170, 120));
        graphicsView_color->setStyleSheet(QString::fromUtf8("background-image: url(:/widget/Picture/Background_5.jpg);"));
        graphicsView_saveOrClear = new QGraphicsView(widget_main);
        graphicsView_saveOrClear->setObjectName(QString::fromUtf8("graphicsView_saveOrClear"));
        graphicsView_saveOrClear->setGeometry(QRect(715, 460, 170, 80));
        QSizePolicy sizePolicy1(QSizePolicy::Fixed, QSizePolicy::Fixed);
        sizePolicy1.setHorizontalStretch(200);
        sizePolicy1.setVerticalStretch(70);
        sizePolicy1.setHeightForWidth(graphicsView_saveOrClear->sizePolicy().hasHeightForWidth());
        graphicsView_saveOrClear->setSizePolicy(sizePolicy1);
        graphicsView_saveOrClear->setMinimumSize(QSize(170, 80));
        graphicsView_saveOrClear->setMaximumSize(QSize(170, 80));
        graphicsView_saveOrClear->setStyleSheet(QString::fromUtf8("background-image: url(:/widget/Picture/Background_6.jpg);"));
        Line_4 = new QFrame(widget_main);
        Line_4->setObjectName(QString::fromUtf8("Line_4"));
        Line_4->setGeometry(QRect(720, 195, 160, 20));
        sizePolicy.setHeightForWidth(Line_4->sizePolicy().hasHeightForWidth());
        Line_4->setSizePolicy(sizePolicy);
        Line_4->setMinimumSize(QSize(160, 20));
        Line_4->setMaximumSize(QSize(160, 20));
        QFont font3;
        font3.setBold(true);
        font3.setWeight(75);
        Line_4->setFont(font3);
        Line_4->setFrameShape(QFrame::HLine);
        Line_4->setFrameShadow(QFrame::Sunken);
        label_2 = new QLabel(widget_main);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(725, 20, 150, 20));
        sizePolicy.setHeightForWidth(label_2->sizePolicy().hasHeightForWidth());
        label_2->setSizePolicy(sizePolicy);
        label_2->setMinimumSize(QSize(150, 20));
        label_2->setMaximumSize(QSize(150, 20));
        QFont font4;
        font4.setFamily(QString::fromUtf8("Agency FB"));
        font4.setPointSize(10);
        font4.setBold(true);
        font4.setItalic(false);
        font4.setWeight(75);
        label_2->setFont(font4);
        label_2->setStyleSheet(QString::fromUtf8(""));
        label_2->setAlignment(Qt::AlignCenter);
        pushButton_clear = new QPushButton(widget_main);
        pushButton_clear->setObjectName(QString::fromUtf8("pushButton_clear"));
        pushButton_clear->setGeometry(QRect(810, 475, 60, 50));
        sizePolicy.setHeightForWidth(pushButton_clear->sizePolicy().hasHeightForWidth());
        pushButton_clear->setSizePolicy(sizePolicy);
        pushButton_clear->setMinimumSize(QSize(60, 50));
        pushButton_clear->setMaximumSize(QSize(60, 50));
        pushButton_clear->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_pen = new QPushButton(widget_main);
        pushButton_pen->setObjectName(QString::fromUtf8("pushButton_pen"));
        pushButton_pen->setGeometry(QRect(730, 40, 50, 50));
        sizePolicy.setHeightForWidth(pushButton_pen->sizePolicy().hasHeightForWidth());
        pushButton_pen->setSizePolicy(sizePolicy);
        pushButton_pen->setMinimumSize(QSize(50, 50));
        pushButton_pen->setMaximumSize(QSize(50, 50));
        pushButton_pen->setFont(font3);
        pushButton_pen->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_pen->setStyleSheet(QString::fromUtf8("background-image: url(:/MainWindow/HomePage/PenMode/source/pen.jpg);"));
        Line_3 = new QFrame(widget_main);
        Line_3->setObjectName(QString::fromUtf8("Line_3"));
        Line_3->setGeometry(QRect(800, 45, 5, 120));
        sizePolicy.setHeightForWidth(Line_3->sizePolicy().hasHeightForWidth());
        Line_3->setSizePolicy(sizePolicy);
        Line_3->setMinimumSize(QSize(5, 120));
        Line_3->setMaximumSize(QSize(5, 120));
        Line_3->setFrameShape(QFrame::VLine);
        Line_3->setFrameShadow(QFrame::Sunken);
        graphicsView_drawPen = new QGraphicsView(widget_main);
        graphicsView_drawPen->setObjectName(QString::fromUtf8("graphicsView_drawPen"));
        graphicsView_drawPen->setGeometry(QRect(715, 20, 170, 170));
        sizePolicy.setHeightForWidth(graphicsView_drawPen->sizePolicy().hasHeightForWidth());
        graphicsView_drawPen->setSizePolicy(sizePolicy);
        graphicsView_drawPen->setMinimumSize(QSize(170, 170));
        graphicsView_drawPen->setMaximumSize(QSize(170, 170));
        graphicsView_drawPen->setStyleSheet(QString::fromUtf8("background-image: url(:/widget/Picture/Background_3.jpg);"));
        pushButton_circle = new QPushButton(widget_main);
        pushButton_circle->setObjectName(QString::fromUtf8("pushButton_circle"));
        pushButton_circle->setGeometry(QRect(730, 120, 50, 50));
        sizePolicy.setHeightForWidth(pushButton_circle->sizePolicy().hasHeightForWidth());
        pushButton_circle->setSizePolicy(sizePolicy);
        pushButton_circle->setMinimumSize(QSize(50, 50));
        pushButton_circle->setMaximumSize(QSize(50, 50));
        QFont font5;
        font5.setKerning(false);
        pushButton_circle->setFont(font5);
        pushButton_circle->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_circle->setStyleSheet(QString::fromUtf8("background-image: url(:/MainWindow/HomePage/PenMode/source/circle.jpg);"));
        pushButton_colorMore = new QPushButton(widget_main);
        pushButton_colorMore->setObjectName(QString::fromUtf8("pushButton_colorMore"));
        pushButton_colorMore->setGeometry(QRect(730, 400, 45, 25));
        sizePolicy.setHeightForWidth(pushButton_colorMore->sizePolicy().hasHeightForWidth());
        pushButton_colorMore->setSizePolicy(sizePolicy);
        pushButton_colorMore->setMinimumSize(QSize(45, 25));
        pushButton_colorMore->setMaximumSize(QSize(45, 25));
        pushButton_colorMore->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_colorMore->setFocusPolicy(Qt::NoFocus);
        pushButton_colorMore->setContextMenuPolicy(Qt::NoContextMenu);
        pushButton_colorMore->setStyleSheet(QString::fromUtf8(""));
        label = new QLabel(widget_main);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(725, 220, 150, 20));
        sizePolicy.setHeightForWidth(label->sizePolicy().hasHeightForWidth());
        label->setSizePolicy(sizePolicy);
        label->setMinimumSize(QSize(150, 20));
        label->setMaximumSize(QSize(150, 20));
        label->setFont(font2);
        label->setAlignment(Qt::AlignCenter);
        label_3 = new QLabel(widget_main);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(725, 310, 150, 20));
        sizePolicy.setHeightForWidth(label_3->sizePolicy().hasHeightForWidth());
        label_3->setSizePolicy(sizePolicy);
        label_3->setMinimumSize(QSize(150, 20));
        label_3->setMaximumSize(QSize(150, 20));
        label_3->setFont(font2);
        label_3->setAlignment(Qt::AlignCenter);
        pushButton_line = new QPushButton(widget_main);
        pushButton_line->setObjectName(QString::fromUtf8("pushButton_line"));
        pushButton_line->setGeometry(QRect(820, 40, 50, 50));
        sizePolicy.setHeightForWidth(pushButton_line->sizePolicy().hasHeightForWidth());
        pushButton_line->setSizePolicy(sizePolicy);
        pushButton_line->setMinimumSize(QSize(50, 50));
        pushButton_line->setMaximumSize(QSize(50, 50));
        pushButton_line->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_line->setStyleSheet(QString::fromUtf8("background-image: url(:/MainWindow/HomePage/PenMode/source/line.jpg);"));
        pushButton_rectangle = new QPushButton(widget_main);
        pushButton_rectangle->setObjectName(QString::fromUtf8("pushButton_rectangle"));
        pushButton_rectangle->setGeometry(QRect(820, 120, 50, 50));
        sizePolicy.setHeightForWidth(pushButton_rectangle->sizePolicy().hasHeightForWidth());
        pushButton_rectangle->setSizePolicy(sizePolicy);
        pushButton_rectangle->setMinimumSize(QSize(50, 50));
        pushButton_rectangle->setMaximumSize(QSize(50, 50));
        pushButton_rectangle->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_rectangle->setStyleSheet(QString::fromUtf8("background-image: url(:/MainWindow/HomePage/PenMode/source/rectangle.jpg);"));
        comboBox_width = new QComboBox(widget_main);
        comboBox_width->addItem(QString());
        comboBox_width->addItem(QString());
        comboBox_width->addItem(QString());
        comboBox_width->addItem(QString());
        comboBox_width->addItem(QString());
        comboBox_width->addItem(QString());
        comboBox_width->addItem(QString());
        comboBox_width->addItem(QString());
        comboBox_width->addItem(QString());
        comboBox_width->addItem(QString());
        comboBox_width->addItem(QString());
        comboBox_width->addItem(QString());
        comboBox_width->addItem(QString());
        comboBox_width->addItem(QString());
        comboBox_width->addItem(QString());
        comboBox_width->addItem(QString());
        comboBox_width->addItem(QString());
        comboBox_width->addItem(QString());
        comboBox_width->addItem(QString());
        comboBox_width->addItem(QString());
        comboBox_width->addItem(QString());
        comboBox_width->addItem(QString());
        comboBox_width->addItem(QString());
        comboBox_width->addItem(QString());
        comboBox_width->addItem(QString());
        comboBox_width->addItem(QString());
        comboBox_width->addItem(QString());
        comboBox_width->addItem(QString());
        comboBox_width->addItem(QString());
        comboBox_width->addItem(QString());
        comboBox_width->addItem(QString());
        comboBox_width->setObjectName(QString::fromUtf8("comboBox_width"));
        comboBox_width->setGeometry(QRect(750, 240, 50, 25));
        sizePolicy.setHeightForWidth(comboBox_width->sizePolicy().hasHeightForWidth());
        comboBox_width->setSizePolicy(sizePolicy);
        comboBox_width->setMinimumSize(QSize(50, 25));
        comboBox_width->setMaximumSize(QSize(50, 25));
        QFont font6;
        font6.setFamily(QString::fromUtf8("Arial Black"));
        font6.setBold(true);
        font6.setWeight(75);
        comboBox_width->setFont(font6);
        comboBox_width->setCursor(QCursor(Qt::PointingHandCursor));
        Line_6 = new QFrame(widget_main);
        Line_6->setObjectName(QString::fromUtf8("Line_6"));
        Line_6->setGeometry(QRect(720, 545, 160, 20));
        sizePolicy.setHeightForWidth(Line_6->sizePolicy().hasHeightForWidth());
        Line_6->setSizePolicy(sizePolicy);
        Line_6->setMinimumSize(QSize(160, 20));
        Line_6->setMaximumSize(QSize(160, 20));
        Line_6->setFont(font3);
        Line_6->setFrameShape(QFrame::HLine);
        Line_6->setFrameShadow(QFrame::Sunken);
        label_6 = new QLabel(widget_main);
        label_6->setObjectName(QString::fromUtf8("label_6"));
        label_6->setGeometry(QRect(780, 400, 35, 25));
        sizePolicy.setHeightForWidth(label_6->sizePolicy().hasHeightForWidth());
        label_6->setSizePolicy(sizePolicy);
        label_6->setMinimumSize(QSize(35, 25));
        label_6->setMaximumSize(QSize(35, 25));
        label_6->setFont(font3);
        label_6->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        graphicsView_width = new QGraphicsView(widget_main);
        graphicsView_width->setObjectName(QString::fromUtf8("graphicsView_width"));
        graphicsView_width->setGeometry(QRect(715, 220, 170, 60));
        sizePolicy.setHeightForWidth(graphicsView_width->sizePolicy().hasHeightForWidth());
        graphicsView_width->setSizePolicy(sizePolicy);
        graphicsView_width->setMinimumSize(QSize(170, 60));
        graphicsView_width->setMaximumSize(QSize(170, 60));
        graphicsView_width->setStyleSheet(QString::fromUtf8("background-image: url(:/widget/Picture/Background_4.jpg);"));
        layoutWidget = new QWidget(widget_main);
        layoutWidget->setObjectName(QString::fromUtf8("layoutWidget"));
        layoutWidget->setGeometry(QRect(730, 330, 143, 69));
        layoutWidget->setCursor(QCursor(Qt::ArrowCursor));
        gridLayout = new QGridLayout(layoutWidget);
        gridLayout->setObjectName(QString::fromUtf8("gridLayout"));
        gridLayout->setContentsMargins(0, 0, 0, 0);
        pushButton_white = new QPushButton(layoutWidget);
        pushButton_white->setObjectName(QString::fromUtf8("pushButton_white"));
        sizePolicy.setHeightForWidth(pushButton_white->sizePolicy().hasHeightForWidth());
        pushButton_white->setSizePolicy(sizePolicy);
        pushButton_white->setMinimumSize(QSize(30, 30));
        pushButton_white->setMaximumSize(QSize(30, 30));
        pushButton_white->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_white->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));

        gridLayout->addWidget(pushButton_white, 1, 3, 1, 1);

        pushButton_black = new QPushButton(layoutWidget);
        pushButton_black->setObjectName(QString::fromUtf8("pushButton_black"));
        sizePolicy.setHeightForWidth(pushButton_black->sizePolicy().hasHeightForWidth());
        pushButton_black->setSizePolicy(sizePolicy);
        pushButton_black->setMinimumSize(QSize(30, 30));
        pushButton_black->setMaximumSize(QSize(30, 30));
        pushButton_black->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_black->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 0);\n"
""));

        gridLayout->addWidget(pushButton_black, 1, 2, 1, 1);

        pushButton_green = new QPushButton(layoutWidget);
        pushButton_green->setObjectName(QString::fromUtf8("pushButton_green"));
        sizePolicy.setHeightForWidth(pushButton_green->sizePolicy().hasHeightForWidth());
        pushButton_green->setSizePolicy(sizePolicy);
        pushButton_green->setMinimumSize(QSize(30, 30));
        pushButton_green->setMaximumSize(QSize(30, 30));
        pushButton_green->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_green->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 255, 0);"));

        gridLayout->addWidget(pushButton_green, 0, 2, 1, 1);

        pushButton_purple = new QPushButton(layoutWidget);
        pushButton_purple->setObjectName(QString::fromUtf8("pushButton_purple"));
        pushButton_purple->setMinimumSize(QSize(30, 30));
        pushButton_purple->setMaximumSize(QSize(30, 30));
        pushButton_purple->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_purple->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 255);"));

        gridLayout->addWidget(pushButton_purple, 1, 1, 1, 1);

        pushButton_blue = new QPushButton(layoutWidget);
        pushButton_blue->setObjectName(QString::fromUtf8("pushButton_blue"));
        sizePolicy.setHeightForWidth(pushButton_blue->sizePolicy().hasHeightForWidth());
        pushButton_blue->setSizePolicy(sizePolicy);
        pushButton_blue->setMinimumSize(QSize(30, 30));
        pushButton_blue->setMaximumSize(QSize(30, 30));
        pushButton_blue->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_blue->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 255);"));

        gridLayout->addWidget(pushButton_blue, 0, 3, 1, 1);

        pushButton_yellow = new QPushButton(layoutWidget);
        pushButton_yellow->setObjectName(QString::fromUtf8("pushButton_yellow"));
        sizePolicy.setHeightForWidth(pushButton_yellow->sizePolicy().hasHeightForWidth());
        pushButton_yellow->setSizePolicy(sizePolicy);
        pushButton_yellow->setMinimumSize(QSize(30, 30));
        pushButton_yellow->setMaximumSize(QSize(30, 30));
        pushButton_yellow->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_yellow->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 0);"));

        gridLayout->addWidget(pushButton_yellow, 0, 1, 1, 1);

        pushButton_red = new QPushButton(layoutWidget);
        pushButton_red->setObjectName(QString::fromUtf8("pushButton_red"));
        sizePolicy.setHeightForWidth(pushButton_red->sizePolicy().hasHeightForWidth());
        pushButton_red->setSizePolicy(sizePolicy);
        pushButton_red->setMinimumSize(QSize(30, 30));
        pushButton_red->setMaximumSize(QSize(30, 30));
        pushButton_red->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_red->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);"));

        gridLayout->addWidget(pushButton_red, 0, 0, 1, 1);

        pushButton_cyan = new QPushButton(layoutWidget);
        pushButton_cyan->setObjectName(QString::fromUtf8("pushButton_cyan"));
        sizePolicy.setHeightForWidth(pushButton_cyan->sizePolicy().hasHeightForWidth());
        pushButton_cyan->setSizePolicy(sizePolicy);
        pushButton_cyan->setMinimumSize(QSize(30, 30));
        pushButton_cyan->setMaximumSize(QSize(30, 30));
        pushButton_cyan->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_cyan->setAutoFillBackground(false);
        pushButton_cyan->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 255, 255);"));

        gridLayout->addWidget(pushButton_cyan, 1, 0, 1, 1);

        pushButton_save = new QPushButton(widget_main);
        pushButton_save->setObjectName(QString::fromUtf8("pushButton_save"));
        pushButton_save->setGeometry(QRect(730, 475, 60, 50));
        sizePolicy.setHeightForWidth(pushButton_save->sizePolicy().hasHeightForWidth());
        pushButton_save->setSizePolicy(sizePolicy);
        pushButton_save->setMinimumSize(QSize(60, 50));
        pushButton_save->setMaximumSize(QSize(60, 50));
        pushButton_save->setCursor(QCursor(Qt::PointingHandCursor));
        Line_5 = new QFrame(widget_main);
        Line_5->setObjectName(QString::fromUtf8("Line_5"));
        Line_5->setGeometry(QRect(720, 285, 160, 20));
        sizePolicy.setHeightForWidth(Line_5->sizePolicy().hasHeightForWidth());
        Line_5->setSizePolicy(sizePolicy);
        Line_5->setMinimumSize(QSize(160, 20));
        Line_5->setMaximumSize(QSize(160, 20));
        Line_5->setFont(font3);
        Line_5->setFrameShape(QFrame::HLine);
        Line_5->setFrameShadow(QFrame::Sunken);
        Line_8 = new QFrame(widget_main);
        Line_8->setObjectName(QString::fromUtf8("Line_8"));
        Line_8->setGeometry(QRect(720, 435, 160, 20));
        sizePolicy.setHeightForWidth(Line_8->sizePolicy().hasHeightForWidth());
        Line_8->setSizePolicy(sizePolicy);
        Line_8->setMinimumSize(QSize(160, 20));
        Line_8->setMaximumSize(QSize(160, 20));
        Line_8->setFont(font3);
        Line_8->setFrameShape(QFrame::HLine);
        Line_8->setFrameShadow(QFrame::Sunken);
        graphicsView_RobbEr = new QGraphicsView(widget_main);
        graphicsView_RobbEr->setObjectName(QString::fromUtf8("graphicsView_RobbEr"));
        graphicsView_RobbEr->setGeometry(QRect(715, 570, 170, 70));
        sizePolicy.setHeightForWidth(graphicsView_RobbEr->sizePolicy().hasHeightForWidth());
        graphicsView_RobbEr->setSizePolicy(sizePolicy);
        graphicsView_RobbEr->setMinimumSize(QSize(170, 70));
        graphicsView_RobbEr->setMaximumSize(QSize(170, 70));
        graphicsView_RobbEr->setStyleSheet(QString::fromUtf8("background-image: url(:/widget/Picture/Background_7.jpg);"));
        pushButton_about = new QPushButton(widget_main);
        pushButton_about->setObjectName(QString::fromUtf8("pushButton_about"));
        pushButton_about->setGeometry(QRect(750, 600, 90, 30));
        sizePolicy.setHeightForWidth(pushButton_about->sizePolicy().hasHeightForWidth());
        pushButton_about->setSizePolicy(sizePolicy);
        pushButton_about->setMinimumSize(QSize(90, 30));
        pushButton_about->setMaximumSize(QSize(90, 30));
        QFont font7;
        font7.setFamily(QString::fromUtf8("Arial"));
        font7.setPointSize(10);
        font7.setBold(true);
        font7.setItalic(true);
        font7.setWeight(75);
        pushButton_about->setFont(font7);
        pushButton_about->setCursor(QCursor(Qt::WhatsThisCursor));
        label_7 = new QLabel(widget_main);
        label_7->setObjectName(QString::fromUtf8("label_7"));
        label_7->setGeometry(QRect(810, 245, 72, 15));
        QFont font8;
        font8.setFamily(QString::fromUtf8("Arial"));
        font8.setPointSize(10);
        font8.setBold(true);
        font8.setWeight(75);
        label_7->setFont(font8);
        label_5->raise();
        graphicsView_actionBar->raise();
        graphicsView_color->raise();
        graphicsView_saveOrClear->raise();
        Line_4->raise();
        pushButton_clear->raise();
        graphicsView_drawPen->raise();
        pushButton_colorMore->raise();
        label_3->raise();
        Line_6->raise();
        label_6->raise();
        layoutWidget->raise();
        pushButton_save->raise();
        pushButton_rectangle->raise();
        pushButton_pen->raise();
        pushButton_circle->raise();
        pushButton_line->raise();
        Line_2->raise();
        label_2->raise();
        Line_3->raise();
        graphicsView_width->raise();
        label->raise();
        comboBox_width->raise();
        Line_5->raise();
        Line_8->raise();
        graphicsView_RobbEr->raise();
        pushButton_about->raise();
        label_color->raise();
        label_4->raise();
        label_7->raise();
        widget_product = new QWidget(centralwidget);
        widget_product->setObjectName(QString::fromUtf8("widget_product"));
        widget_product->setGeometry(QRect(0, 100, 900, 650));
        sizePolicy.setHeightForWidth(widget_product->sizePolicy().hasHeightForWidth());
        widget_product->setSizePolicy(sizePolicy);
        widget_product->setMinimumSize(QSize(900, 650));
        widget_product->setMaximumSize(QSize(900, 650));
        widget_about = new QWidget(centralwidget);
        widget_about->setObjectName(QString::fromUtf8("widget_about"));
        widget_about->setGeometry(QRect(0, 0, 900, 650));
        sizePolicy.setHeightForWidth(widget_about->sizePolicy().hasHeightForWidth());
        widget_about->setSizePolicy(sizePolicy);
        widget_about->setMinimumSize(QSize(900, 650));
        widget_about->setMaximumSize(QSize(900, 650));
        label_user = new QLabel(widget_about);
        label_user->setObjectName(QString::fromUtf8("label_user"));
        label_user->setGeometry(QRect(120, 170, 100, 50));
        sizePolicy.setHeightForWidth(label_user->sizePolicy().hasHeightForWidth());
        label_user->setSizePolicy(sizePolicy);
        label_user->setMinimumSize(QSize(100, 50));
        label_user->setMaximumSize(QSize(100, 50));
        QFont font9;
        font9.setFamily(QString::fromUtf8("Arial"));
        font9.setPointSize(18);
        font9.setBold(true);
        font9.setWeight(75);
        label_user->setFont(font9);
        label_user->setFrameShape(QFrame::NoFrame);
        label_user->setFrameShadow(QFrame::Sunken);
        label_username = new QLabel(widget_about);
        label_username->setObjectName(QString::fromUtf8("label_username"));
        label_username->setGeometry(QRect(230, 170, 300, 50));
        sizePolicy.setHeightForWidth(label_username->sizePolicy().hasHeightForWidth());
        label_username->setSizePolicy(sizePolicy);
        label_username->setMinimumSize(QSize(300, 50));
        label_username->setMaximumSize(QSize(300, 50));
        label_username->setFont(font9);
        label_username->setFrameShape(QFrame::NoFrame);
        label_username->setFrameShadow(QFrame::Sunken);
        label_pass = new QLabel(widget_about);
        label_pass->setObjectName(QString::fromUtf8("label_pass"));
        label_pass->setGeometry(QRect(120, 220, 100, 50));
        sizePolicy.setHeightForWidth(label_pass->sizePolicy().hasHeightForWidth());
        label_pass->setSizePolicy(sizePolicy);
        label_pass->setMinimumSize(QSize(100, 50));
        label_pass->setMaximumSize(QSize(100, 50));
        label_pass->setFont(font9);
        label_pass->setFrameShape(QFrame::NoFrame);
        label_pass->setFrameShadow(QFrame::Sunken);
        pushButton_change = new QPushButton(widget_about);
        pushButton_change->setObjectName(QString::fromUtf8("pushButton_change"));
        pushButton_change->setGeometry(QRect(220, 220, 100, 50));
        QFont font10;
        font10.setFamily(QString::fromUtf8("Arial"));
        font10.setPointSize(14);
        font10.setBold(true);
        font10.setWeight(75);
        pushButton_change->setFont(font10);
        pushButton_change->setCursor(QCursor(Qt::PointingHandCursor));
        label_change = new QLabel(widget_about);
        label_change->setObjectName(QString::fromUtf8("label_change"));
        label_change->setGeometry(QRect(120, 270, 100, 50));
        sizePolicy.setHeightForWidth(label_change->sizePolicy().hasHeightForWidth());
        label_change->setSizePolicy(sizePolicy);
        label_change->setMinimumSize(QSize(100, 50));
        label_change->setMaximumSize(QSize(100, 50));
        label_change->setFont(font9);
        label_change->setFrameShape(QFrame::NoFrame);
        label_change->setFrameShadow(QFrame::Sunken);
        lineEdit_change = new QLineEdit(widget_about);
        lineEdit_change->setObjectName(QString::fromUtf8("lineEdit_change"));
        lineEdit_change->setGeometry(QRect(230, 280, 220, 30));
        sizePolicy.setHeightForWidth(lineEdit_change->sizePolicy().hasHeightForWidth());
        lineEdit_change->setSizePolicy(sizePolicy);
        lineEdit_change->setMinimumSize(QSize(220, 30));
        lineEdit_change->setMaximumSize(QSize(220, 30));
        pushButton_yes = new QPushButton(widget_about);
        pushButton_yes->setObjectName(QString::fromUtf8("pushButton_yes"));
        pushButton_yes->setGeometry(QRect(120, 320, 150, 30));
        sizePolicy.setHeightForWidth(pushButton_yes->sizePolicy().hasHeightForWidth());
        pushButton_yes->setSizePolicy(sizePolicy);
        pushButton_yes->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_no = new QPushButton(widget_about);
        pushButton_no->setObjectName(QString::fromUtf8("pushButton_no"));
        pushButton_no->setGeometry(QRect(300, 320, 150, 30));
        sizePolicy.setHeightForWidth(pushButton_no->sizePolicy().hasHeightForWidth());
        pushButton_no->setSizePolicy(sizePolicy);
        pushButton_no->setCursor(QCursor(Qt::PointingHandCursor));
        MainWindow->setCentralWidget(centralwidget);
        widget_about->raise();
        widget_nav->raise();
        widget_main->raise();
        widget_product->raise();

        retranslateUi(MainWindow);

        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "\346\267\263\346\267\263\347\224\273\346\235\2772.0", nullptr));
        pushButton_personal->setText(QApplication::translate("MainWindow", "\344\270\252\344\272\272\344\277\241\346\201\257", nullptr));
        pushButton_main->setText(QApplication::translate("MainWindow", "\347\273\230\347\224\273", nullptr));
        pushButton_product->setText(QApplication::translate("MainWindow", "\344\275\234\345\223\201", nullptr));
        label_5->setText(QApplication::translate("MainWindow", "@", nullptr));
        label_color->setText(QString());
        label_4->setText(QApplication::translate("MainWindow", "\345\210\266\344\275\234\344\272\272\345\221\230", nullptr));
        label_2->setText(QApplication::translate("MainWindow", "\347\224\273\347\254\224\347\261\273\345\236\213", nullptr));
        pushButton_clear->setText(QApplication::translate("MainWindow", "\346\270\205\345\261\217", nullptr));
        pushButton_pen->setText(QString());
        pushButton_circle->setText(QString());
        pushButton_colorMore->setText(QApplication::translate("MainWindow", "\346\233\264\345\244\232", nullptr));
        label->setText(QApplication::translate("MainWindow", "\347\262\227\347\273\206", nullptr));
        label_3->setText(QApplication::translate("MainWindow", "\351\242\234\350\211\262", nullptr));
        pushButton_line->setText(QString());
        pushButton_rectangle->setText(QString());
        comboBox_width->setItemText(0, QApplication::translate("MainWindow", "1", nullptr));
        comboBox_width->setItemText(1, QApplication::translate("MainWindow", "2", nullptr));
        comboBox_width->setItemText(2, QApplication::translate("MainWindow", "3", nullptr));
        comboBox_width->setItemText(3, QApplication::translate("MainWindow", "4", nullptr));
        comboBox_width->setItemText(4, QApplication::translate("MainWindow", "5", nullptr));
        comboBox_width->setItemText(5, QApplication::translate("MainWindow", "6", nullptr));
        comboBox_width->setItemText(6, QApplication::translate("MainWindow", "7", nullptr));
        comboBox_width->setItemText(7, QApplication::translate("MainWindow", "8", nullptr));
        comboBox_width->setItemText(8, QApplication::translate("MainWindow", "9", nullptr));
        comboBox_width->setItemText(9, QApplication::translate("MainWindow", "10", nullptr));
        comboBox_width->setItemText(10, QApplication::translate("MainWindow", "11", nullptr));
        comboBox_width->setItemText(11, QApplication::translate("MainWindow", "12", nullptr));
        comboBox_width->setItemText(12, QApplication::translate("MainWindow", "13", nullptr));
        comboBox_width->setItemText(13, QApplication::translate("MainWindow", "14", nullptr));
        comboBox_width->setItemText(14, QApplication::translate("MainWindow", "15", nullptr));
        comboBox_width->setItemText(15, QApplication::translate("MainWindow", "16", nullptr));
        comboBox_width->setItemText(16, QApplication::translate("MainWindow", "17", nullptr));
        comboBox_width->setItemText(17, QApplication::translate("MainWindow", "18", nullptr));
        comboBox_width->setItemText(18, QApplication::translate("MainWindow", "19", nullptr));
        comboBox_width->setItemText(19, QApplication::translate("MainWindow", "20", nullptr));
        comboBox_width->setItemText(20, QApplication::translate("MainWindow", "25", nullptr));
        comboBox_width->setItemText(21, QApplication::translate("MainWindow", "30", nullptr));
        comboBox_width->setItemText(22, QApplication::translate("MainWindow", "35", nullptr));
        comboBox_width->setItemText(23, QApplication::translate("MainWindow", "40", nullptr));
        comboBox_width->setItemText(24, QApplication::translate("MainWindow", "45", nullptr));
        comboBox_width->setItemText(25, QApplication::translate("MainWindow", "50", nullptr));
        comboBox_width->setItemText(26, QApplication::translate("MainWindow", "60", nullptr));
        comboBox_width->setItemText(27, QApplication::translate("MainWindow", "70", nullptr));
        comboBox_width->setItemText(28, QApplication::translate("MainWindow", "80", nullptr));
        comboBox_width->setItemText(29, QApplication::translate("MainWindow", "90", nullptr));
        comboBox_width->setItemText(30, QApplication::translate("MainWindow", "100", nullptr));

        label_6->setText(QApplication::translate("MainWindow", "\345\275\223\345\211\215", nullptr));
        pushButton_white->setText(QString());
        pushButton_black->setText(QString());
        pushButton_green->setText(QString());
        pushButton_purple->setText(QString());
        pushButton_blue->setText(QString());
        pushButton_yellow->setText(QString());
        pushButton_red->setText(QString());
        pushButton_cyan->setText(QString());
        pushButton_save->setText(QApplication::translate("MainWindow", "\344\277\235\345\255\230", nullptr));
        pushButton_about->setText(QApplication::translate("MainWindow", "@RobbEr", nullptr));
        label_7->setText(QApplication::translate("MainWindow", "px", nullptr));
        label_user->setText(QApplication::translate("MainWindow", "\347\224\250\346\210\267\345\220\215:", nullptr));
        label_username->setText(QApplication::translate("MainWindow", "XXXXXXXXXXX", nullptr));
        label_pass->setText(QApplication::translate("MainWindow", "\345\257\206\347\240\201:", nullptr));
        pushButton_change->setText(QApplication::translate("MainWindow", "\344\277\256\346\224\271\345\257\206\347\240\201", nullptr));
        label_change->setText(QApplication::translate("MainWindow", "\346\226\260\345\257\206\347\240\201:", nullptr));
        pushButton_yes->setText(QApplication::translate("MainWindow", "\347\241\256\350\256\244\346\233\264\346\224\271", nullptr));
        pushButton_no->setText(QApplication::translate("MainWindow", "\345\217\226\346\266\210\345\271\266\350\277\224\345\233\236", nullptr));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
